name: Push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
permissions:
  contents: read
jobs:
  x86_64:
    name: x86_64
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      - name: apt
        run: |
          apt update -y
          DEBIAN_FRONTEND=noninteractive apt install -y clang make php-cli libcapstone4 libcapstone-dev
      - name: make
        # gcc has unknown linking issues with capstone, so we're using clang for now
        run: make CC=clang BUILD_CC=clang TARGET=x86_64 all
      - name: test
        run: make CC=clang BUILD_CC=clang TARGET=x86_64 test-ci
  x86_32:
    name: x86_32
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      - name: apt
        run: |
          dpkg --add-architecture i386
          apt update -y
          DEBIAN_FRONTEND=noninteractive apt install -y clang gcc gcc-multilib make php-cli libc6:i386 wget
      - name: Build capstone
        run: |
          # capstone isn't distributed for 32-bit so we need to build it manually
          wget https://github.com/capstone-engine/capstone/archive/4.0.2.tar.gz -O capstone.tar.gz
          tar zxvf capstone.tar.gz
          cd capstone-4.0.2
          ./make.sh nix32
          ./make.sh install
          cd ..
          rm -rf capstone-4.0.2 capstone.tar.gz
      - name: make
        run: make CC=clang BUILD_CC=clang TARGET=x86 all
      - name: test
        run: make CC=clang BUILD_CC=clang TARGET=x86 test-ci
  aarch64:
    name: aarch64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            apt update -y
            DEBIAN_FRONTEND=noninteractive apt install -y gcc clang make php-cli libc6 libcapstone4 libcapstone-dev
          run: |
            make CC=clang BUILD_CC=clang TARGET=aarch64 all
            # FIXME: For some reason some of the object files are rebuilt
            make CC=clang BUILD_CC=clang TARGET=aarch64 test-ci
